// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP2o2GyzADTiRyx2GOfSrerOtKkUzfRYk',
    appId: '1:401695407956:web:7aa883427890de590392c1',
    messagingSenderId: '401695407956',
    projectId: 'sistema-pnsa-85f9a',
    authDomain: 'sistema-pnsa-85f9a.firebaseapp.com',
    storageBucket: 'sistema-pnsa-85f9a.firebasestorage.app',
    measurementId: 'G-73130MTBKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACrytvidP2QDvihAAOcJkfiuF7OlOzrrA',
    appId: '1:401695407956:android:750efb74e09a09bf0392c1',
    messagingSenderId: '401695407956',
    projectId: 'sistema-pnsa-85f9a',
    storageBucket: 'sistema-pnsa-85f9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCWc5UaE2qj2EI8Piw0k9Ffvxtmv0wKOM',
    appId: '1:401695407956:ios:b2a03740d313b5780392c1',
    messagingSenderId: '401695407956',
    projectId: 'sistema-pnsa-85f9a',
    storageBucket: 'sistema-pnsa-85f9a.firebasestorage.app',
    iosBundleId: 'com.pnsa.plataformaPnsaCatequese',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCWc5UaE2qj2EI8Piw0k9Ffvxtmv0wKOM',
    appId: '1:401695407956:ios:b2a03740d313b5780392c1',
    messagingSenderId: '401695407956',
    projectId: 'sistema-pnsa-85f9a',
    storageBucket: 'sistema-pnsa-85f9a.firebasestorage.app',
    iosBundleId: 'com.pnsa.plataformaPnsaCatequese',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP2o2GyzADTiRyx2GOfSrerOtKkUzfRYk',
    appId: '1:401695407956:web:a733768d6e2ec9e80392c1',
    messagingSenderId: '401695407956',
    projectId: 'sistema-pnsa-85f9a',
    authDomain: 'sistema-pnsa-85f9a.firebaseapp.com',
    storageBucket: 'sistema-pnsa-85f9a.firebasestorage.app',
    measurementId: 'G-TLCGVBJKEP',
  );
}
